[package]
name = "synapse-delegation"
version = "0.1.0"
authors = ["DerFetzer <kontakt@der-fetzer.de>"]
edition = "2018"

[dependencies]
rocket = "0.4.11"
rocket_contrib = { version = "0.4.10", default-features = false, features = ["json"] }
